"""Generates structurally/cryptographically forged Secured I-PDUs (SR-01, SR-04)."""
from enum import Enum

from sim.can_bus import CanBus
from sim.config import DEFAULT_AUTHENTICATOR_LENGTH, DEFAULT_FRESHNESS_LENGTH
from sim.message_injector import MessageInjector

_FORGED_AUTHENTIC_PDU = b"\xDE\xAD\xBE\xEF"
_INVALID_MAC = b"\xFF" * DEFAULT_AUTHENTICATOR_LENGTH
_VALID_RANGE_TRUNCATED_FRESHNESS = 1
_OUT_OF_WINDOW_TRUNCATED_FRESHNESS = (1 << (DEFAULT_FRESHNESS_LENGTH * 8)) - 1


class ForgeMode(str, Enum):
    """Categories of forged Secured I-PDU generated by FuzzingEngine."""

    MALFORMED_STRUCTURE = "MALFORMED_STRUCTURE"
    INVALID_MAC = "INVALID_MAC"
    WRONG_FRESHNESS = "WRONG_FRESHNESS"


class FuzzingEngine:
    """Generates and injects forged Secured I-PDUs onto the simulated bus."""

    def __init__(self, can_bus: CanBus, injector: MessageInjector) -> None:
        self._can_bus = can_bus
        self._injector = injector

    def generate_forged_pdu(self, pdu_id, mode: ForgeMode) -> bytes:
        """Generate a forged Secured I-PDU per the requested ForgeMode.

        Args:
            pdu_id: Logical PDU identifier (used for context only).
            mode: ForgeMode describing how the PDU should be forged.

        Returns:
            Forged Secured I-PDU bytes.
        """
        if mode == ForgeMode.MALFORMED_STRUCTURE:
            # Shorter than freshness_length + authenticator_length: cannot
            # be parsed into authentic_pdu || freshness || mac.
            return b"\x00"

        if mode == ForgeMode.WRONG_FRESHNESS:
            freshness_value = _OUT_OF_WINDOW_TRUNCATED_FRESHNESS
        else:
            freshness_value = _VALID_RANGE_TRUNCATED_FRESHNESS

        freshness_bytes = freshness_value.to_bytes(DEFAULT_FRESHNESS_LENGTH, "big")
        return _FORGED_AUTHENTIC_PDU + freshness_bytes + _INVALID_MAC

    def inject(self, pdu_id, pdu: bytes) -> None:
        """Inject a forged PDU onto the bus.

        Args:
            pdu_id: Logical PDU identifier.
            pdu: Forged Secured I-PDU bytes.
        """
        self._injector.inject(pdu_id, pdu)
